#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 22 20:36:51 2018

@author: grzegorzjuszkiewicz
"""
def setMessage():
    return input("Podaj wiadomość do zaszyfrowania/zdeszyfrowania:")


def stringToChar():
    message=setMessage()
    chars=[]
    for word in message:
        for letter in word:
            chars.append(letter)
    return chars
            

def psswdPrep(code):
    message=stringToChar()
    code_list=[]


stringToChar()